// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: io/message.proto

package io

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IOStatus int32

const (
	IOStatus_IOSuccess IOStatus = 0
	IOStatus_IOK       IOStatus = 1
	IOStatus_IBusy     IOStatus = 2
	IOStatus_ITimeout  IOStatus = 3
	IOStatus_IFailed   IOStatus = 4
	IOStatus_OOK       IOStatus = 5
	IOStatus_OEMPTY    IOStatus = 6
	IOStatus_OBusy     IOStatus = 7
	IOStatus_OTimeout  IOStatus = 8
	IOStatus_OFailed   IOStatus = 9
)

// Enum value maps for IOStatus.
var (
	IOStatus_name = map[int32]string{
		0: "IOSuccess",
		1: "IOK",
		2: "IBusy",
		3: "ITimeout",
		4: "IFailed",
		5: "OOK",
		6: "OEMPTY",
		7: "OBusy",
		8: "OTimeout",
		9: "OFailed",
	}
	IOStatus_value = map[string]int32{
		"IOSuccess": 0,
		"IOK":       1,
		"IBusy":     2,
		"ITimeout":  3,
		"IFailed":   4,
		"OOK":       5,
		"OEMPTY":    6,
		"OBusy":     7,
		"OTimeout":  8,
		"OFailed":   9,
	}
)

func (x IOStatus) Enum() *IOStatus {
	p := new(IOStatus)
	*p = x
	return p
}

func (x IOStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IOStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_io_message_proto_enumTypes[0].Descriptor()
}

func (IOStatus) Type() protoreflect.EnumType {
	return &file_io_message_proto_enumTypes[0]
}

func (x IOStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IOStatus.Descriptor instead.
func (IOStatus) EnumDescriptor() ([]byte, []int) {
	return file_io_message_proto_rawDescGZIP(), []int{0}
}

type IOMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataType string `protobuf:"bytes,1,opt,name=DataType,proto3" json:"DataType,omitempty"`
	Coding   string `protobuf:"bytes,2,opt,name=Coding,proto3" json:"Coding,omitempty"`
	Compress string `protobuf:"bytes,3,opt,name=Compress,proto3" json:"Compress,omitempty"`
	Payload  []byte `protobuf:"bytes,4,opt,name=Payload,proto3" json:"Payload,omitempty"`
}

func (x *IOMessage) Reset() {
	*x = IOMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_io_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IOMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IOMessage) ProtoMessage() {}

func (x *IOMessage) ProtoReflect() protoreflect.Message {
	mi := &file_io_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IOMessage.ProtoReflect.Descriptor instead.
func (*IOMessage) Descriptor() ([]byte, []int) {
	return file_io_message_proto_rawDescGZIP(), []int{0}
}

func (x *IOMessage) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *IOMessage) GetCoding() string {
	if x != nil {
		return x.Coding
	}
	return ""
}

func (x *IOMessage) GetCompress() string {
	if x != nil {
		return x.Compress
	}
	return ""
}

func (x *IOMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type IOMessageBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IOMessageBatch []*IOMessage `protobuf:"bytes,1,rep,name=IOMessageBatch,proto3" json:"IOMessageBatch,omitempty"`
}

func (x *IOMessageBatch) Reset() {
	*x = IOMessageBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_io_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IOMessageBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IOMessageBatch) ProtoMessage() {}

func (x *IOMessageBatch) ProtoReflect() protoreflect.Message {
	mi := &file_io_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IOMessageBatch.ProtoReflect.Descriptor instead.
func (*IOMessageBatch) Descriptor() ([]byte, []int) {
	return file_io_message_proto_rawDescGZIP(), []int{1}
}

func (x *IOMessageBatch) GetIOMessageBatch() []*IOMessage {
	if x != nil {
		return x.IOMessageBatch
	}
	return nil
}

type IOResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  IOStatus `protobuf:"varint,1,opt,name=Status,proto3,enum=io.IOStatus" json:"Status,omitempty"`
	Message string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Coding  string   `protobuf:"bytes,3,opt,name=Coding,proto3" json:"Coding,omitempty"`
	Payload []byte   `protobuf:"bytes,4,opt,name=Payload,proto3" json:"Payload,omitempty"`
}

func (x *IOResponse) Reset() {
	*x = IOResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_io_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IOResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IOResponse) ProtoMessage() {}

func (x *IOResponse) ProtoReflect() protoreflect.Message {
	mi := &file_io_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IOResponse.ProtoReflect.Descriptor instead.
func (*IOResponse) Descriptor() ([]byte, []int) {
	return file_io_message_proto_rawDescGZIP(), []int{2}
}

func (x *IOResponse) GetStatus() IOStatus {
	if x != nil {
		return x.Status
	}
	return IOStatus_IOSuccess
}

func (x *IOResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *IOResponse) GetCoding() string {
	if x != nil {
		return x.Coding
	}
	return ""
}

func (x *IOResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_io_message_proto protoreflect.FileDescriptor

var file_io_message_proto_rawDesc = []byte{
	0x0a, 0x10, 0x69, 0x6f, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x69, 0x6f, 0x22, 0x75, 0x0a, 0x09, 0x49, 0x4f, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x43, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x43, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x70, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x6f, 0x6d, 0x70, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x47, 0x0a,
	0x0e, 0x49, 0x4f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12,
	0x35, 0x0a, 0x0e, 0x49, 0x4f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x69, 0x6f, 0x2e, 0x49, 0x4f, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0e, 0x49, 0x4f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x22, 0x7e, 0x0a, 0x0a, 0x49, 0x4f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x69, 0x6f, 0x2e, 0x49, 0x4f, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x43, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2a, 0x83, 0x01, 0x0a, 0x08, 0x49, 0x4f, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x0d, 0x0a, 0x09, 0x49, 0x4f, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x49,
	0x42, 0x75, 0x73, 0x79, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x54, 0x69, 0x6d, 0x65, 0x6f,
	0x75, 0x74, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10,
	0x04, 0x12, 0x07, 0x0a, 0x03, 0x4f, 0x4f, 0x4b, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x45,
	0x4d, 0x50, 0x54, 0x59, 0x10, 0x06, 0x12, 0x09, 0x0a, 0x05, 0x4f, 0x42, 0x75, 0x73, 0x79, 0x10,
	0x07, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x10, 0x08, 0x12,
	0x0b, 0x0a, 0x07, 0x4f, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x09, 0x32, 0x9d, 0x01, 0x0a,
	0x14, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x0d, 0x2e,
	0x69, 0x6f, 0x2e, 0x49, 0x4f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0e, 0x2e, 0x69,
	0x6f, 0x2e, 0x49, 0x4f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x09,
	0x53, 0x65, 0x6e, 0x64, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x12, 0x2e, 0x69, 0x6f, 0x2e, 0x49,
	0x4f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x1a, 0x0e, 0x2e,
	0x69, 0x6f, 0x2e, 0x49, 0x4f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a,
	0x0a, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x0d, 0x2e, 0x69, 0x6f,
	0x2e, 0x49, 0x4f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0e, 0x2e, 0x69, 0x6f, 0x2e,
	0x49, 0x4f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x42, 0x21, 0x5a, 0x1f,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x43, 0x6f, 0x64, 0x61, 0x70,
	0x65, 0x57, 0x69, 0x6c, 0x64, 0x2f, 0x64, 0x65, 0x76, 0x6b, 0x69, 0x74, 0x2f, 0x69, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_io_message_proto_rawDescOnce sync.Once
	file_io_message_proto_rawDescData = file_io_message_proto_rawDesc
)

func file_io_message_proto_rawDescGZIP() []byte {
	file_io_message_proto_rawDescOnce.Do(func() {
		file_io_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_io_message_proto_rawDescData)
	})
	return file_io_message_proto_rawDescData
}

var file_io_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_io_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_io_message_proto_goTypes = []interface{}{
	(IOStatus)(0),          // 0: io.IOStatus
	(*IOMessage)(nil),      // 1: io.IOMessage
	(*IOMessageBatch)(nil), // 2: io.IOMessageBatch
	(*IOResponse)(nil),     // 3: io.IOResponse
}
var file_io_message_proto_depIdxs = []int32{
	1, // 0: io.IOMessageBatch.IOMessageBatch:type_name -> io.IOMessage
	0, // 1: io.IOResponse.Status:type_name -> io.IOStatus
	1, // 2: io.MessageReportService.Send:input_type -> io.IOMessage
	2, // 3: io.MessageReportService.SendBatch:input_type -> io.IOMessageBatch
	1, // 4: io.MessageReportService.SendStream:input_type -> io.IOMessage
	3, // 5: io.MessageReportService.Send:output_type -> io.IOResponse
	3, // 6: io.MessageReportService.SendBatch:output_type -> io.IOResponse
	3, // 7: io.MessageReportService.SendStream:output_type -> io.IOResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_io_message_proto_init() }
func file_io_message_proto_init() {
	if File_io_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_io_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IOMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_io_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IOMessageBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_io_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IOResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_io_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_io_message_proto_goTypes,
		DependencyIndexes: file_io_message_proto_depIdxs,
		EnumInfos:         file_io_message_proto_enumTypes,
		MessageInfos:      file_io_message_proto_msgTypes,
	}.Build()
	File_io_message_proto = out.File
	file_io_message_proto_rawDesc = nil
	file_io_message_proto_goTypes = nil
	file_io_message_proto_depIdxs = nil
}
